package cn.com.alien.user.model.db;

public class SystemUserModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_SYSTEM_USER.ID
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_SYSTEM_USER.USER_NAME
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_SYSTEM_USER.USER_PASSWD
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    private String userPasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_SYSTEM_USER.USER_ID_CODE
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    private String userIdCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_SYSTEM_USER.USER_ID
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB_SYSTEM_USER.USER_MAC
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    private String userMac;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_SYSTEM_USER.ID
     *
     * @return the value of DB_SYSTEM_USER.ID
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_SYSTEM_USER.ID
     *
     * @param id the value for DB_SYSTEM_USER.ID
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_SYSTEM_USER.USER_NAME
     *
     * @return the value of DB_SYSTEM_USER.USER_NAME
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_SYSTEM_USER.USER_NAME
     *
     * @param userName the value for DB_SYSTEM_USER.USER_NAME
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_SYSTEM_USER.USER_PASSWD
     *
     * @return the value of DB_SYSTEM_USER.USER_PASSWD
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public String getUserPasswd() {
        return userPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_SYSTEM_USER.USER_PASSWD
     *
     * @param userPasswd the value for DB_SYSTEM_USER.USER_PASSWD
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public void setUserPasswd(String userPasswd) {
        this.userPasswd = userPasswd == null ? null : userPasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_SYSTEM_USER.USER_ID_CODE
     *
     * @return the value of DB_SYSTEM_USER.USER_ID_CODE
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public String getUserIdCode() {
        return userIdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_SYSTEM_USER.USER_ID_CODE
     *
     * @param userIdCode the value for DB_SYSTEM_USER.USER_ID_CODE
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public void setUserIdCode(String userIdCode) {
        this.userIdCode = userIdCode == null ? null : userIdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_SYSTEM_USER.USER_ID
     *
     * @return the value of DB_SYSTEM_USER.USER_ID
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_SYSTEM_USER.USER_ID
     *
     * @param userId the value for DB_SYSTEM_USER.USER_ID
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB_SYSTEM_USER.USER_MAC
     *
     * @return the value of DB_SYSTEM_USER.USER_MAC
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public String getUserMac() {
        return userMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB_SYSTEM_USER.USER_MAC
     *
     * @param userMac the value for DB_SYSTEM_USER.USER_MAC
     *
     * @mbg.generated Sat Jul 22 23:25:28 CST 2017
     */
    public void setUserMac(String userMac) {
        this.userMac = userMac == null ? null : userMac.trim();
    }
}